### ISSUE TITLE
Limit the script to only editor admin pages?

### ISSUE THREAD

**Issue by srikat** [aduth/wp-disable-nux#1]
Hi,

Here via https://github.com/WordPress/gutenberg/issues/19512#issuecomment-572304859.

Would it make sense to use code similar to https://github.com/Freemius/wordpress-sdk/commit/8a87d389c647b4588bfe96fc7d420d62a48cbac5 to restrict the inline script to only the admin pages where Gutenberg editor is actually being used?

**Comment by aduth** [comment]
Hey @srikat !

If I recall correctly, it should already be working this way. The hook is run on `admin_enqueue_scripts` (admin screens only), and the hook itself attaches an inline script to `wp-nux`, but doesn't actually _enqueue_ `wp-nux`, so it would only take effect on screens where `wp-nux` is already enqueued (i.e. the editor screen).
